const products = [
    { id: 1, name: 'Xiaomi Redmi Note 13', value: 621.34, category: 'beauty', mark: 'Xiaomi' },
    { id: 2, name: 'Iphone 14', value: 398.73, category: 'furniture', mark: 'Apple' },
    { id: 3, name: 'Samsung Galaxy S21', value: 351.84, category: 'food', mark: 'Samsung' },
    { id: 4, name: 'Sony Alpha 7C', value: 948.91, category: 'electronics', mark: 'Sony' },
    { id: 5, name: 'LG G Pad 5', value: 272.49, category: 'electronics', mark: 'LG' },
    { id: 6, name: 'Adidas T-shirt', value: 864.51, category: 'sports', mark: 'Adidas' },
    { id: 7, name: 'Apple Watch Series 7', value: 706.92, category: 'electronics', mark: 'Apple' },
    { id: 8, name: 'Xiaomi Mi 11', value: 835.26, category: 'sports', mark: 'Xiaomi' },
    { id: 9, name: 'Samsung Galaxy Watch 4', value: 808.76, category: 'sports', mark: 'Samsung' },
    { id: 10, name: 'Sony Cyber-shot DSC-RX100', value: 883.74, category: 'furniture', mark: 'Sony' },
    { id: 11, name: 'Apple Watch SE', value: 478.91, category: 'sports', mark: 'Apple' },
    { id: 12, name: 'Xiaomi Mi 10', value: 181.84, category: 'sports', mark: 'Xiaomi' },
    { id: 13, name: 'Nike Sports T-shirt', value: 591.49, category: 'furniture', mark: 'Nike' },
    { id: 14, name: 'iPad Air 4', value: 729.43, category: 'sports', mark: 'Apple' },
    { id: 15, name: 'Samsung Galaxy Z Flip 4', value: 412.76, category: 'beauty', mark: 'Samsung' },
    { id: 16, name: 'LG Velvet', value: 209.49, category: 'food', mark: 'LG' },
    { id: 17, name: 'Adidas Performance Shirt', value: 108.51, category: 'sports', mark: 'Adidas' },
    { id: 18, name: 'Xiaomi Mi Band 6', value: 812.46, category: 'beauty', mark: 'Xiaomi' },
    { id: 19, name: 'Samsung Galaxy Tab S6', value: 487.93, category: 'electronics', mark: 'Samsung' },
    { id: 20, name: 'Sony WH-1000XM4', value: 501.49, category: 'electronics', mark: 'Sony' },
    { id: 21, name: 'Iphone 13 Mini', value: 895.11, category: 'sports', mark: 'Apple' },
    { id: 22, name: 'Samsung Galaxy Tab A7', value: 670.83, category: 'beauty', mark: 'Samsung' },
    { id: 23, name: 'Apple MacBook Air', value: 694.84, category: 'electronics', mark: 'Apple' },
    { id: 24, name: 'Canon EOS M50', value: 308.87, category: 'food', mark: 'Canon' },
    { id: 25, name: 'Samsung Galaxy A72', value: 249.53, category: 'food', mark: 'Samsung' },
    { id: 26, name: 'Microsoft Surface Pro 7', value: 984.76, category: 'beauty', mark: 'Microsoft' },
    { id: 27, name: 'Iphone 12 Pro', value: 935.88, category: 'sports', mark: 'Apple' },
    { id: 28, name: 'Fossil Hybrid HR', value: 124, category: 'sports', mark: 'Fossil' },
    { id: 29, name: 'Nikon D3500', value: 101.74, category: 'sports', mark: 'Nikon' },
    { id: 30, name: 'Apple iPhone XR', value: 283.93, category: 'electronics', mark: 'Apple' },
    { id: 31, name: 'Puma Sports T-shirt', value: 869.31, category: 'furniture', mark: 'Puma' },
    { id: 32, name: 'LG Gram Laptop', value: 611.94, category: 'furniture', mark: 'LG' },
    { id: 33, name: 'Sony WH-CH700N', value: 839.77, category: 'sports', mark: 'Sony' },
    { id: 34, name: 'Iphone 14 Pro Max', value: 941.68, category: 'sports', mark: 'Apple' },
    { id: 35, name: 'Samsung Galaxy S22 Ultra', value: 699.74, category: 'sports', mark: 'Samsung' },
    { id: 36, name: 'Sony Xperia 1 II', value: 872.54, category: 'electronics', mark: 'Sony' },
    { id: 37, name: 'Sony WH-1000XM5', value: 775.87, category: 'electronics', mark: 'Sony' },
    { id: 38, name: 'Iphone 13 Pro', value: 364.88, category: 'sports', mark: 'Apple' },
    { id: 39, name: 'Casio G-Shock', value: 124.84, category: 'furniture', mark: 'Casio' },
    { id: 40, name: 'Samsung Galaxy S20 FE', value: 657.68, category: 'furniture', mark: 'Samsung' },
    { id: 41, name: 'Bose QuietComfort 35', value: 482.46, category: 'food', mark: 'Bose' },
    { id: 42, name: 'Garmin Fenix 6', value: 828.61, category: 'sports', mark: 'Garmin' },
    { id: 43, name: 'Nike Sports Shirt', value: 381.61, category: 'beauty', mark: 'Nike' },
    { id: 44, name: 'Canon EOS Rebel T7', value: 963.11, category: 'furniture', mark: 'Canon' },
    { id: 45, name: 'Garmin Forerunner 45', value: 575.97, category: 'food', mark: 'Garmin' },
    { id: 46, name: 'Google Pixel 6', value: 368.27, category: 'electronics', mark: 'Google' },
    { id: 47, name: 'Nike Training Shirt', value: 425.97, category: 'beauty', mark: 'Nike' },
    { id: 48, name: 'Samsung Galaxy Z Fold 4', value: 815.39, category: 'sports', mark: 'Samsung' },
    { id: 49, name: 'Canon EOS 90D', value: 704.56, category: 'electronics', mark: 'Canon' },
    { id: 50, name: 'Iphone 11 Pro', value: 624.38, category: 'sports', mark: 'Apple' },
    { id: 51, name: 'Microsoft Surface Laptop 3', value: 306.87, category: 'sports', mark: 'Microsoft' },
    { id: 52, name: 'Iphone SE', value: 819.92, category: 'electronics', mark: 'Apple' },
    { id: 53, name: 'Samsung Galaxy S10', value: 708.84, category: 'sports', mark: 'Samsung' },
    { id: 54, name: 'Sony WH-XB700', value: 321.13, category: 'sports', mark: 'Sony' },
    { id: 55, name: 'Iphone 13', value: 728.44, category: 'beauty', mark: 'Apple' },
    { id: 56, name: 'Garmin Venu 2', value: 204.71, category: 'food', mark: 'Garmin' },
    { id: 58, name: 'Samsung Galaxy S21 FE', value: 456.76, category: 'sports', mark: 'Samsung' },
    { id: 59, name: 'Iphone 8', value: 629.46, category: 'electronics', mark: 'Apple' },
    { id: 60, name: 'Sony Xperia 5 II', value: 243.69, category: 'electronics', mark: 'Sony' },
    { id: 61, name: 'Canon EOS M6 Mark II', value: 998.82, category: 'food', mark: 'Canon' },
    { id: 62, name: 'Iphone X', value: 682.98, category: 'sports', mark: 'Apple' },
    { id: 63, name: 'Nikon D7500', value: 486.71, category: 'sports', mark: 'Nikon' },
    { id: 64, name: 'Sony WH-1000XM3', value: 717.61, category: 'sports', mark: 'Sony' },
    { id: 65, name: 'Samsung Galaxy A52', value: 748.68, category: 'sports', mark: 'Samsung' },
    { id: 66, name: 'Google Pixel 5', value: 841.71, category: 'sports', mark: 'Google' },
    { id: 67, name: 'Samsung Galaxy Watch Active2', value: 746.49, category: 'sports', mark: 'Samsung' },
    { id: 68, name: 'Apple MacBook Pro 13"', value: 119.41, category: 'sports', mark: 'Apple' },
    { id: 69, name: 'Iphone 14 Plus', value: 281.49, category: 'electronics', mark: 'Apple' },
    { id: 70, name: 'Sony Xperia 10 II', value: 518.39, category: 'sports', mark: 'Sony' },
    { id: 71, name: 'Nikon Z7 II', value: 799.59, category: 'electronics', mark: 'Nikon' },
    { id: 72, name: 'Xiaomi Mi 9', value: 364.92, category: 'electronics', mark: 'Xiaomi' },
    { id: 73, name: 'Iphone 13 Pro Max', value: 918.71, category: 'beauty', mark: 'Apple' },
    { id: 75, name: 'Samsung Galaxy Note 20', value: 213.87, category: 'electronics', mark: 'Samsung' },
    { id: 76, name: 'Sony Xperia XZ3', value: 245.18, category: 'sports', mark: 'Sony' },
    { id: 77, name: 'Iphone 12 Mini', value: 712.49, category: 'sports', mark: 'Apple' },
    { id: 78, name: 'Huawei P30 Pro', value: 817.62, category: 'sports', mark: 'Huawei' },
    { id: 79, name: 'Oppo Reno 4 Pro', value: 306.23, category: 'beauty', mark: 'Oppo' },
    { id: 80, name: 'Samsung Galaxy S10e', value: 295.61, category: 'sports', mark: 'Samsung' },
    { id: 81, name: 'Xiaomi Mi Mix 4', value: 584.19, category: 'electronics', mark: 'Xiaomi' },
    { id: 82, name: 'Iphone 11', value: 101.56, category: 'beauty', mark: 'Apple' },
    { id: 83, name: 'Nikon D850', value: 625.83, category: 'food', mark: 'Nikon' },
    { id: 84, name: 'Sony ZV-1', value: 376.69, category: 'sports', mark: 'Sony' },
    { id: 85, name: 'Google Pixel 4a', value: 199.61, category: 'electronics', mark: 'Google' },
    { id: 86, name: 'Iphone XR', value: 549.73, category: 'beauty', mark: 'Apple' },
    { id: 87, name: 'Garmin Fenix 5', value: 732.58, category: 'sports', mark: 'Garmin' },
    { id: 88, name: 'Huawei Mate 20 Pro', value: 729.64, category: 'sports', mark: 'Huawei' },
    { id: 89, name: 'Iphone 12', value: 412.18, category: 'beauty', mark: 'Apple' },
    { id: 90, name: 'Canon EOS 5D Mark IV', value: 638.57, category: 'furniture', mark: 'Canon' },
    { id: 91, name: 'Sony Xperia 1', value: 724.82, category: 'beauty', mark: 'Sony' },
    { id: 92, name: 'Google Pixel 6 Pro', value: 294.88, category: 'sports', mark: 'Google' },
    { id: 93, name: 'Iphone 11 Pro Max', value: 146.57, category: 'beauty', mark: 'Apple' },
    { id: 94, name: 'Oppo A93', value: 791.19, category: 'sports', mark: 'Oppo' },
    { id: 95, name: 'Iphone 14 Pro', value: 499.99, category: 'sports', mark: 'Apple' },
    { id: 96, name: 'Samsung Galaxy Note 10', value: 482.73, category: 'furniture', mark: 'Samsung' },
    { id: 97, name: 'Huawei P40 Pro', value: 623.18, category: 'electronics', mark: 'Huawei' },
    { id: 98, name: 'Nikon Z6', value: 971.59, category: 'electronics', mark: 'Nikon' },
    { id: 99, name: 'Iphone 7', value: 184.72, category: 'electronics', mark: 'Apple' },
    { id: 100, name: 'Google Pixel 3', value: 741.65, category: 'electronics', mark: 'Google' }
]

export {
    products,
}
  

 